export const GEOCITY_LOADING = 'GEOCITY_LOADING';
export const GEOCITY_LOADING_ERROR =  'GEOCITY_LOADING_ERROR';
export const GEOCITY_LOADING_SUCCESS = 'GEOCITY_LOADING_SUCCESS';
export const ADD_FAV = 'ADD_FAV';
export const UPDATE_FAV = 'UPDATE_FAV';
export const ADD_FAV_LOADING = 'ADD_FAV_LOADING';
export const REMOVE_FAV = 'REMOVE_FAV';
export const LOAD_ERROR = 'LOAD_ERROR';